language: python
notifications:
    irc: "chat.freenote.net#pil"

dist: trusty
sudo: required
services:
    - docker

install:
    - sudo apt-get install -qyy debootstrap
    - make update

script:
    - make build
    - make test
