language: python
notifications:
    irc: "chat.freenote.net#pil"

dist: trusty
services:
    - docker

matrix:
  fast_finish: true
  include:
    - env: DOCKER="alpine"
    - env: DOCKER="amazon-1-amd64"
    - env: DOCKER="amazon-2-amd64"
    - env: DOCKER="arch"
    - env: DOCKER="centos-6-amd64"
    - env: DOCKER="centos-7-amd64"
    - env: DOCKER="fedora-26-amd64"
    - env: DOCKER="fedora-27-amd64"
    - env: DOCKER="ubuntu-trusty-x86"
    - env: DOCKER="ubuntu-xenial-amd64"
    - env: DOCKER="debian-stretch-x86"

install:
    - sudo apt-get update && sudo apt-get install -qyy debootstrap
    - sudo chown -R 1000 $TRAVIS_BUILD_DIR
    - cd "$DOCKER" && make update

script:
    - make build && make test
