language: python
notifications:
    irc: "chat.freenote.net#pil"

dist: trusty
sudo: required
services:
    - docker

install:
    - sudo apt-get install -qyy debootstrap
    - sudo ln -s /usr/share/debootstrap/scripts/sid /usr/share/debootstrap/scripts/stretch
    - make -j4 update

script:
    - make build
    - make test
